name: Build

on:
  workflow_call:

permissions:
  contents: read
  checks: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v5
      with:
          go-version: 1.22.1
    - name: Install XPortal
      run: |
        go install go.lumeweb.com/xportal/cmd/xportal@latest
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
          submodules: true
    - name: Extract Repo Name
      id: repo-name
      run: echo "REPO_NAME=$(echo ${{ github.repository }} | cut -d '/' -f 2)" >> $GITHUB_OUTPUT
    - name: Build
      run: |
          PLUGIN=$(readlink -f .)
          xportal build --with go.lumeweb.com/${{ steps.repo-name.outputs.REPO_NAME }} --replace go.lumeweb.com/${{ steps.repo-name.outputs.REPO_NAME }}=$PLUGIN